apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: pvr
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8686
  selector:
    app: lidarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: pvr
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: bv11-cr01.bessems.eu/proxy/linuxserver/lidarr:nightly
        ports:
          - name: web
            containerPort: 8686
        volumeMounts:
        - mountPath: /config
          name: flexvolsmb-lidarr-config
        - mountPath: /songs
          name: flexvolsmb-pvr-songs
        - mountPath: /downloads-amd
          name: smb-pvr-volatile
          subPath: downloads
      - name: amd
        image: bv11-cr01.bessems.eu/library/automatedmusicdownloader
        env:
        - name: AUTOSTART
          value: 'true'
        - name: FORMAT
          value: MP3
        - name: BITRATE
          value: '320'
        - name: LidarrUrl
          value: http://lidarr.pvr.svc.cluster.local:8686
        - name: LidarrAPIkey
          value: 1e11c5d649ab4c70b3f91792bc91821b
        - name: ARL_TOKEN
          value: f173fa3b790a1fe0f7c89f2ed99efefc64e66ddb2f9e9cc397b780bdd567d256788039f1c27c5e1dd59511d93e721b3d84fa90767aafb77ed619fb05dd9123e4fd3cdaaefb5f237b1aedcec595f65eb419ee55a5df82ce3d3e658bbbb624e21e
        volumeMounts:
        - mountPath: /config
          name: flexvolsmb-lidarr-amd
        - mountPath: /downloads-amd
          name: smb-pvr-volatile
          subPath: downloads
      volumes:
      - name: flexvolsmb-lidarr-config
        persistentVolumeClaim:
          claimName: flexvolsmb-lidarr-config
      - name: flexvolsmb-lidarr-amd
        persistentVolumeClaim:
          claimName: flexvolsmb-lidarr-amd
      - name: flexvolsmb-pvr-songs
        persistentVolumeClaim:
          claimName: flexvolsmb-pvr-songs
      - name: smb-pvr-volatile
        persistentVolumeClaim:
          claimName: smb-pvr-volatile
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
  namespace: pvr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`songs.pvr.spamasaurus.com`)
    kind: Rule
    services:
    - name: lidarr
      port: 8686
    middlewares:
      - name: 2fa-authentication@file
      - name: security-headers@file
      - name: compression@file
  tls:
    options:
      name: defaults@file
    certResolver: default
    domains:
    - main: '*.pvr.spamasaurus.com'
      sans:
        - 'pvr.spamasaurus.com'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-lidarr-config
  namespace: pvr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-lidarr-config
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,iocharset=utf8,nobrl
      server: 192.168.11.225
      share: /K3s.Volumes/lidarr/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-lidarr-config
  namespace: pvr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-lidarr-config
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-lidarr-amd
  namespace: pvr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-lidarr-amd
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0666,dir_mode=0766,uid=911,gid=911,iocharset=utf8
      server: 192.168.11.225
      share: /K3s.Volumes/lidarr/amd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-lidarr-amd
  namespace: pvr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-lidarr-amd
  resources:
    requests:
      storage: 1Gi
