apiVersion: v1
kind: Service
metadata:
  name: nzbhydra
spec:
  ports:
    - protocol: TCP
      port: 5076
      targetPort: 5076
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nzbhydra
subsets:
  - addresses:
      - ip: 192.168.11.242
    ports:
      - port: 5076
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nzbhydra
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`index.pvr.spamasaurus.com`)
    kind: Rule
    services:
      - name: nzbhydra
        port: 5076
    middlewares:
      - name: 2fa-authentication@file
      - name: security-headers@file
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
---
apiVersion: v1
kind: Endpoints
metadata:
  name: radarr
subsets:
  - addresses:
      - ip: 192.168.11.242
    ports:
      - port: 7878
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`movies.pvr.spamasaurus.com`)
    kind: Rule
    services:
      - name: radarr
        port: 7878
    middlewares:
      - name: 2fa-authentication@file
      - name: security-headers@file
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sabnzbd
subsets:
  - addresses:
      - ip: 192.168.11.242
    ports:
      - port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`download.pvr.spamasaurus.com`)
    kind: Rule
    services:
      - name: sabnzbd
        port: 8080
    middlewares:
      - name: 2fa-authentication@file
      - name: security-headers@file
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sonarr
subsets:
  - addresses:
      - ip: 192.168.11.242
    ports:
      - port: 8989
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`series.pvr.spamasaurus.com`)
    kind: Rule
    services:
      - name: sonarr
        port: 8989
    middlewares:
      - name: 2fa-authentication@file
      - name: security-headers@file
