apiVersion: v1
kind: Service
metadata:
  name: readarr
  namespace: pvr
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8787
  selector:
    app: readarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  namespace: pvr
  labels:
    app: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      containers:
      - name: readarr
        image: hotio/readarr:nightly
        env:
        - name: DEBUG
          value: 'yes'
        ports:
          - name: web
            containerPort: 8787
        volumeMounts:
        - mountPath: /config
          name: flexvolsmb-readarr-config
        - mountPath: /books
          name: flexvolsmb-pvr-books
        - mountPath: /downloads
          name: smb-pvr-volatile
          subPath: downloads
      volumes:
      - name: flexvolsmb-readarr-config
        persistentVolumeClaim:
          claimName: flexvolsmb-readarr-config
      - name: flexvolsmb-pvr-books
        persistentVolumeClaim:
          claimName: flexvolsmb-pvr-books
      - name: smb-pvr-volatile
        persistentVolumeClaim:
          claimName: smb-pvr-volatile
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: readarr
  namespace: pvr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`books.pvr.spamasaurus.com`)
    kind: Rule
    services:
    - name: readarr
      port: 8787
    middlewares:
    - name: 2fa-authentication@file
    - name: security-headers@file
    - name: compression@file
  tls:
    options:
      name: defaults@file
    certResolver: default
    domains:
    - main: '*.pvr.spamasaurus.com'
      sans:
        - 'pvr.spamasaurus.com'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-readarr-config
  namespace: pvr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-readarr-config
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,uid=1000,gid=1000,iocharset=utf8,nobrl
      server: 192.168.11.225
      share: /K3s.Volumes/readarr/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-readarr-config
  namespace: pvr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-readarr-config
  resources:
    requests:
      storage: 1Gi
