apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-pvr-movies
  namespace: pvr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-pvr-movies
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,uid=911,gid=911,iocharset=utf8,cache=none
      server: 192.168.11.225
      share: /Public/Video's/Films
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-pvr-movies
  namespace: pvr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-pvr-movies
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-pvr-series
  namespace: pvr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-pvr-series
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,uid=911,gid=911,iocharset=utf8,cache=none
      server: 192.168.11.225
      share: /Public/Video's/Series
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-pvr-series
  namespace: pvr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-pvr-series
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-pvr-books
  namespace: pvr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-pvr-books
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,iocharset=utf8,cache=none
      server: 192.168.11.225
      share: /Public/Boeken
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-pvr-books
  namespace: pvr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-pvr-books
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-pvr-songs
  namespace: pvr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-pvr-songs
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,iocharset=utf8,cache=none
      server: 192.168.11.225
      share: /Public/Audio/temp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-pvr-songs
  namespace: pvr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-pvr-songs
  resources:
    requests:
      storage: 1Gi
