apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`storage.spamasaurus.com`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
          namespace: longhorn-system
      middlewares:
        - name: 2fa-authentication@file
        - name: security-headers@file
        - name: compression@file
