apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: bv11-cr01.bessems.eu/proxy/rancher/k3s-upgrade:v1.19.3-k3s2
  serviceAccountName: system-upgrade
  upgrade:
    image: bv11-cr01.bessems.eu/proxy/rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
