apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-adminer-conf
data:
  login-password-less.php: |
    <?php
      require_once('plugins/login-password-less.php');

      /** Set allowed password
      * @param string result of password_hash
      */
      return new AdminerLoginPasswordLess(
        $password_hash = password_hash(rtrim(file_get_contents('/vault/secrets/sqlitepw')), PASSWORD_DEFAULT)
      );
    ?>
