apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-sqlitepw: "secret/adminer"
        vault.hashicorp.com/role: "adminer"
        vault.hashicorp.com/agent-inject-template-sqlitepw: |
          {{ with secret "secret/adminer" -}}
            {{ .Data.data.sqlitepw }}
          {{- end }}
      labels:
        app: adminer
    spec:
      serviceAccountName: adminer
      containers:
      - name: adminer
        image: registry.spamasaurus.com/proxy/library/adminer
        ports:
          - name: web
            containerPort: 8080
        volumeMounts:
        - mountPath: /mnt/websites
          name: flexvolsmb-adminer-websites
        - name: configmap-adminer-conf
          mountPath: /var/www/html/plugins-enabled/login-password-less.php
          subPath: login-password-less.php
      volumes:
      - name: flexvolsmb-adminer-websites
        persistentVolumeClaim:
          claimName: flexvolsmb-adminer-websites
      - name: configmap-adminer-conf
        configMap:
          name: configmap-adminer-conf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adminer
  labels:
    app: adminer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adminer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`sql.spamasaurus.com`)
    kind: Rule
    services:
    - name: adminer
      port: 8080
    middlewares:
      - name: 2fa-authentication@file
      - name: security-headers@file
      - name: compression@file
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-adminer-websites
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-adminer-websites
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,iocharset=utf8,nobrl
      server: 192.168.11.225
      share: /K3s.Volumes/lighttpd/websites
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-adminer-websites
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-adminer-websites
  resources:
    requests:
      storage: 1Gi
