apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-certs-dumper
  labels:
    app: traefik-certs-dumper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-certs-dumper
  template:
    metadata:
      labels:
        app: traefik-certs-dumper
    spec:
      containers:
      - name: traefik-certs-dumper
        image: bv11-cr01.bessems.eu/proxy/ldez/traefik-certs-dumper:latest-amd64
        command: ['traefik-certs-dumper', 'file']
        args: 
        - --watch
        - --version=v2
        - --source=/data/source/acme.json
        - --dest=/data/export/
        - --domain-subdir
        volumeMounts:
        - mountPath: /data/source/acme.json
          name: flexvolsmb-traefikcertsdumper-acmejson
          subPath: acme.json
          readOnly: true
        - mountPath: /data/export
          name: flexvolsmb-traefikcertsdumper-export
      volumes:
      - name: flexvolsmb-traefikcertsdumper-acmejson
        persistentVolumeClaim:
          claimName: flexvolsmb-traefikcertsdumper-acmejson
      - name: flexvolsmb-traefikcertsdumper-export
        persistentVolumeClaim:
          claimName: flexvolsmb-traefikcertsdumper-export
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-traefikcertsdumper-acmejson
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-traefikcertsdumper-acmejson
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0600,dir_mode=0600,iocharset=utf8,nobrl
      server: 192.168.11.225
      share: /K3s.Volumes/traefik/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-traefikcertsdumper-acmejson
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-traefikcertsdumper-acmejson
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-traefikcertsdumper-export
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-traefikcertsdumper-export
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,iocharset=utf8,nobrl
      server: 192.168.11.225
      share: /K3s.Volumes/traefikcertsdumper/export
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-traefikcertsdumper-export
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-traefikcertsdumper-export
  resources:
    requests:
      storage: 1Gi
