apiVersion: v1
kind: Service
metadata:
  name: harbor
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: harbor
subsets:
  - addresses:
      - ip: 192.168.11.249
    ports:
      - port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`registry.spamasaurus.com`)
    kind: Rule
    services:
    - name: harbor
      port: 80
    middlewares:
      - name: security-headers@file
      - name: compression@file
#  - match: Host(`registry.spamasaurus.com`) && PathPrefix(`/api/`, `/service/`, `/v2/`, `/chartrepo/`, `/c/`)
#    kind: Rule
#    services:
#    - name: harbor-harbor-core
#      port: 80
#    middlewares:
#      - name: security-headers@file
#  - match: Host(`notary.spamasaurus.com`)
#    kind: Rule
#    services:
#    - name: harbor-harbor-notary-server
#      port: 4443
#    middlewares:
#      - name: security-headers@file
