apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-lighttpd-conf
data:
  lighttpd.conf: |
    server.modules = (
        "mod_access",
        "mod_alias",
        "mod_compress",
        "mod_redirect",
        "mod_rewrite",
    )

    server.document-root        = "/var/www/html"
    server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
    server.errorlog             = "/var/log/lighttpd/error.log"
    server.pid-file             = "/var/run/lighttpd.pid"
    server.username             = "www-data"
    server.groupname            = "www-data"
    server.port                 = 8080

    index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
    url.access-deny             = ( "~", ".inc" )
    static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

    compress.cache-dir          = "/var/cache/lighttpd/compress/"
    compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

    include_shell "/usr/share/lighttpd/create-mime.assign.pl"
    include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
    include_shell "cat /etc/lighttpd/vhosts.d/*.conf"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-lighttpd-vhosts
data:
  bessems.com.conf: |
    $HTTP["host"] =~ "^bessems\.(com|eu)$" {
      server.document-root = "/var/www/bessems.com/"
    }
  gabaldon.eu.conf: |
    $HTTP["host"] =~ "^gabaldon\.(eu|nl)$" {
      server.document-root = "/var/www/gabaldon.eu/"
    }
  sn.itch.fyi.conf: |
    $HTTP["host"] == "sn.itch.fyi" {
      server.document-root = "/var/www/sn.itch.fyi/"

      index-file.names += ("/_h5ai/public/index.php")
    }
  spamasaurus.com.conf: |
    $HTTP["host"] == "spamasaurus.com" {
      server.document-root = "/var/www/spamasaurus.com/public"

      index-file.names += ("spamasaurusRex.login.php")
    }
    $HTTP["url"] =~ "^/.well-known/" {
      mimetype.assign   += ( "server" => "application/json" )
    }
  sw.itch.fyi.conf: |
    $HTTP["host"] == "sw.itch.fyi" {
      server.document-root = "/var/www/sw.itch.fyi/"

      url.rewrite-once = (
        "^/api\?(.*)" => "index.php?page=newznabapi&$1"
      )
    }
