apiVersion: v1
kind: Service
metadata:
  name: lighttpd
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: lighttpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighttpd
  labels:
    app: lighttpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighttpd
  template:
    metadata:
      labels:
        app: lighttpd
    spec:
      containers:
      - name: lighttpd-php-pwsh
        image: bv11-cr01.bessems.eu/library/lighttpd-php-powershell
        ports:
          - name: web
            containerPort: 8080
        volumeMounts:
        - name: configmap-lighttpd-conf
          mountPath: /etc/lighttpd/lighttpd.conf
          subPath: lighttpd.conf
        - name: configmap-lighttpd-vhosts
          mountPath: /etc/lighttpd/vhosts.d
        - name: flexvolsmb-lighttpd-data
          mountPath: /data/scripts
        - name: flexvolsmb-lighttpd-websites
          mountPath: /var/www/
      volumes:
      - name: configmap-lighttpd-conf
        configMap:
          name: configmap-lighttpd-conf
      - name: configmap-lighttpd-vhosts
        configMap:
          name: configmap-lighttpd-vhosts
      - name: flexvolsmb-lighttpd-data
        persistentVolumeClaim:
          claimName: flexvolsmb-lighttpd-data
      - name: flexvolsmb-lighttpd-websites
        persistentVolumeClaim:
          claimName: flexvolsmb-lighttpd-websites
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lighttpd
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`bessems.com`) || Host(`bessems.eu`) || Host(`gabaldon.eu`) || Host(`gabaldon.nl`) || Host(`sn.itch.fyi`) || Host(`sw.itch.fyi`) || Host(`spamasaurus.com`)
    kind: Rule
    services:
    - name: lighttpd
      port: 8080
    middlewares:
    - name: security-headers@file
    - name: compression@file
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-lighttpd-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-lighttpd-data
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,iocharset=utf8
      server: 192.168.11.225
      share: /K3s.Volumes/lighttpd/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexvolsmb-lighttpd-websites
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-lighttpd-websites
  flexVolume:
    driver: mount/smb
    secretRef:
      name: smb-secret
    options:
      opts: domain=bessems.eu,file_mode=0777,dir_mode=0777,iocharset=utf8,nobrl
      server: 192.168.11.225
      share: /K3s.Volumes/lighttpd/websites
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-lighttpd-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-lighttpd-data
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexvolsmb-lighttpd-websites
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: flexvolsmb-lighttpd-websites
  resources:
    requests:
      storage: 1Gi
